services:
  emby-panel:
    image: dannis1514/emby-panel:beta
    container_name: emby-panel
    ports:
      - "8080:80"
    volumes:
      - ./config.php:/var/www/html/config.php:rw
      - ./data:/data
      - ./logs:/logs
    environment:
      TZ: Asia/Shanghai
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
