services:
  emby-panel:
    image: dannis1514/emby-panel:beta
    container_name: emby-panel
    ports:
      - "8080:80"
    volumes:
      - ./config.php:/var/www/html/config.php:ro
      - ./data:/data  #自动创建
      - ./logs:/logs  #自动创建
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
